@startuml is001_regardApplicationCausesInquiringServiceRecords_Problem1
skinparam responseMessageBelowArrow true

title
is001_regardApplicationCausesInquiringServiceRecords_Problem1
end title

participant "EATL://v1/regard-application" as eatlRegardApplication
participant "EATL://v1/update-operation-key" as eatlUpdateOperationKey

participant "newApp://v1/redirect-service-request-information" as newAppRedirectSerReqInfo
participant "newApp://v1/update-operation-key" as newAppUpdateOperationKey
database "newApp:config.json" as newAppConfiguration

participant "ALT://v1/add-operation-client-to-link" as altAddOperClient2Link
participant "ALT://v1/update-ltp" as altUpdateLtp
database "ALT:ElasticSearch" as altApplicationDataES

participant "OKM://v1/regard-updated-link" as okmRegardUpdatedLink

group Initial data
    note over newAppConfiguration #LightBlue
        version of EATL is 2.0.1
        {
        "application-name" : "ExecutionAndTraceLog",
        <b>"release-number" : "2.0.1"
        }
    end note
    note over altApplicationDataES #LightBlue
        In the control-construct of the newApplication,
        version of EATL is 2.0.1
        {
        "application-name" : "ExecutionAndTraceLog",
        <b>"release-number" : "2.0.1"
        }
    end note
end

note over eatlRegardApplication
    <b>Step 1
    initiates link craetion for
    "/v1/redirect-service-request-information"
    in the serving application(NewApplication)
    and the client application(ExecutionAndTraceLog)
end note

eatlRegardApplication -> altAddOperClient2Link : <b>Step 1

note Right altAddOperClient2Link
    <b>Step 2
    notifies new link creation to OKM
end note

altAddOperClient2Link -> okmRegardUpdatedLink : <b>Step 2

note over okmRegardUpdatedLink
    <b>Step 3
    OKM generates new operation-key and 
    it will try to set the new <b>operation-key 
    to the client application<b>(ExecutionAndTraceLog)
    and the serving application<b>(NewApplication)
end note

okmRegardUpdatedLink -> newAppUpdateOperationKey : <b>Step 3.1
okmRegardUpdatedLink -> eatlUpdateOperationKey : <b>Step 3.2
eatlUpdateOperationKey -[#Grey]> eatlRegardApplication : Internally informs about the operation-key update

note over eatlRegardApplication
    <b>Step 4
    After receiving an updated operation-key
    for the operation-client
    "/v1/redirect-service-request-information"
    of the NewApplication , 
    NewApp://v1/redirect-service-request-information
    will be addressed
end note

eatlRegardApplication -> newAppRedirectSerReqInfo : <b>Step 4
newAppRedirectSerReqInfo -> eatlRegardApplication : responseCode : 204

group callback of "newApplicationname://v1/redirect-service-request-information"
    newAppRedirectSerReqInfo --> newAppConfiguration
    note over newAppConfiguration #LightBlue
        version of EATL is 2.1.0
        {
        "application-name" : "ExecutionAndTraceLog",
        <b>"release-number" : "2.1.0"
        }
    end note
    newAppConfiguration --> altUpdateLtp
    altUpdateLtp --> altApplicationDataES
    note over altApplicationDataES #LightBlue
        In the control-construct of the newApplication,
        version of EATL is 2.1.0
        {
        "application-name" : "ExecutionAndTraceLog",
        <b>"release-number" : "2.1.0"
        }
    end note
end

note over eatlRegardApplication
    <b>Step 5
    initiates link creation for 
    "/v1/record-service-request"
    in the serving application(ExecutionAndTraceLog)
    and the client application(NewApplication)
end note

eatlRegardApplication -> altAddOperClient2Link : <b>Step 5

note over altAddOperClient2Link #LightCoral
    link creation will be successful
    <b>Only if the 
    <b>callback of "newApplicationName://v1/redirect-service-request-information"
    <b>completed its job before this step.
end note






